server:
  port: 8991

spring:
  application:
    name: my-shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bhz
    password: Bhz123456
    url: jdbc:mysql://localhost:3306/firstDoc?serverTimezone=UTC
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 允许按照驼峰命名法映射

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8991/eureka
    register-with-eureka: true
    fetch-registry: true

